language: node_js
node_js:
  - "11.3.0"
notifications:
  email:
    recipients:
      - f789852@gmail.com
    on_success: always # default: change
    on_failure: always # default: always
cache: npm
env:
  - secure: "eecr1XvldKbZUCKMPplugZlKII4F+tLRkN5JZwy0PPhRkJ5kjPzmP+K+zI4Ioakqajs3pvInSywUgqt3OLP1i6oPXLWKdcHC/qewHvzgDlDFyt/hwp2gVujlzfKE2adOO6iYRCay/PYI0spPGI7bLxzHLF6mk5MYU4xT7Qt2iuXC31CISzDlt32RSdXAP+JJ+RTFNsbbv+4nlmuonHdFHdC42ub07REZ5F1NO9mJHUqFHiUFuNsEnoYrXscfzKKJtECjO3RlYPV5ndbspeXUpSkslPLGLMMdd9bcI7q6nmBNCJdn5/7ZX0jn/jkJTW1DshDzMHuehUQyFsQrO5wUsR126ptzdBb+UsW7hgezmJ/Iy5zaLk6INKruQ4nPACpOKETPDZcLtG5aaw4tc1ALopmeGVXA6yDZzSjM+xLJuCMqBDIkNJXoNm4QkYn8QyivFwRwY0Hu/fjrQzuHkH72YjwsTTfBmeazfHKzbKNYoz9PMSJlq9mfzDEVIoh+K4dgOIGyusGq92MYkvLbvlRK82ZxpDEUTARrEeyGnK1eoHKrXXWbPTgBi1vE4cJi2h9WkH1YCjtAuvVS9IGBRHY8RTh8oigWnEGFuJ4qrdEBvwAnNkkPq70BUuK/rBeKtPjj2KOQ+cWnbkIS9PK2zebF3IiCnhirFRu0AaycOOHqdgY="
after_success:
  - "curl -o /tmp/travis-automerge https://raw.githubusercontent.com/cdown/travis-automerge/master/travis-automerge"
  - "chmod a+x /tmp/travis-automerge"
  - "BRANCHES_TO_MERGE_REGEX='^feature/' BRANCH_TO_MERGE_INTO=master GITHUB_REPO=FuFunG/node_backend /tmp/travis-automerge"